name: Deploy preview

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: preview

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Use Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Build 🏗️
        run: npm run build
        env:
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      - name: Deploy to gharchive-live.surge.sh 🚀
        uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: './build'
          teardown: true
          build: echo 'already built'
