name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Build for production 🏗️
        run: npm run build
        if: ${{ github.event_name != 'pull_request' }}
        env:
          API_BASE: ${{ secrets.API_BASE_PRODUCTION }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN_PRODUCTION }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID_PRODUCTION }}
          AUTH0_CALLBACK_URL: ${{ secrets.AUTH0_CALLBACK_URL_PRODUCTION }}
      - name: Build for preview 🏗️
        run: npm run build
        if: ${{ github.event_name == 'pull_request' }}
        env:
          API_BASE: ${{ secrets.API_BASE_PREVIEW }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN_PREVIEW }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID_PREVIEW }}
          AUTH0_CALLBACK_URL: ${{ secrets.AUTH0_CALLBACK_URL_PREVIEW }}
      - name: Deploy to gharchive.live 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
      - name: Deploy to gharchive-live.surge.sh 🚀
        uses: afc163/surge-preview@v1
        if: ${{ github.event_name == 'pull_request' }}
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: './build'
          teardown: true
          build: echo 'already built'
